name: build

on: 
  push:
    branches:
      - develop
      - release_*
    tags:
      - v*
    
  pull_request:
    branches: 
    - develop
    - release_*

jobs:
  build:
    name: Build
    runs-on: windows-latest
    # info about windows-latest https://github.com/actions/runner-images
    env:
      DROP_DIR: drop
    steps:
      - uses: actions/checkout@v1
      - name: Build Everything
        shell: powershell
        run: ./build.ps1
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: release_drop
          path: ${{ env.DROP_DIR }}